name: testing

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  spread-sheet-converter-testing:
    name: SpreadSheetConverter (PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }})
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8.0','8.1']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Version
        run: |
          cat /etc/os-release
          php -v
          composer --version

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Install php-cs-fixer
        run: composer bin tools require friendsofphp/php-cs-fixer

      - name: Install php_codesniffer
        run: composer bin tools require squizlabs/php_codesniffer

      - name: Execute tests via PHPUnit
        run: vendor/bin/phpunit

      - name: PHP CS Fixer Run
        run: vendor/bin/php-cs-fixer fix -v --diff --dry-run

      - name: Execute tests via phpcs
        run: vendor/bin/phpcs --standard=phpcs.xml ./

      - name: Execute tests via phpstan
        run: vendor/bin/phpstan analyse
